[package]
name = "pipeline"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
csv = "1.3.0"
postgres = { version = "0.19.9", features = ["with-chrono-0_4"] }
serde = { version = "1.0.210", features = ["derive"] }
